# Generated by Django 4.0.7 on 2022-09-23 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='token',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.token'),
        ),
    ]
