# Generated by Django 4.0.7 on 2022-09-23 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_alter_history_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='image',
            field=models.ImageField(default='bitcoin_icon.jpg', upload_to='token_logo'),
        ),
    ]
