# Generated by Django 4.1.1 on 2022-09-15 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                default="default_avatar.jpg", upload_to="profile_pics"
            ),
        ),
    ]
